### ISSUE TITLE
Uncaught error: Hydraton failed due to Mismatch

### ISSUE THREAD

**Issue by LiteSoul** [rphlmr/supa-stripe-stack#13]
Hiya, so first thanks for this starter.
I've managed to get it working, however if we peek into de dev console we see a few errors related to Hydration fail, so it switches to client rendering...
Your demo has it too: https://remix-supa-stripe-stack.fly.dev/ . Although on dev you can see the errors un-minified.

Also when seeding the DB and Stripe, had to do it manually due to "run-s" not being recognized on npm run setup. I don't think an extra package is worth it for that anyways?

Thanks!

![Screenshot 2023-09-07 165950](https://github.com/rphlmr/supa-stripe-stack/assets/22918889/0cf68aed-b41b-4ddd-a148-08a6a97f6ed5)

**Comment by rphlmr** [comment]
Hello, will look at that as soon as possible.
Thanks for reporting.

**Comment by LiteSoul** [comment]
This problem disappeared for some reason, closing issue.

**Comment by LiteSoul** [comment]
This problem disappeared for some reason, closing issue.
