### ISSUE TITLE
Be sure it works with Remix v2

### ISSUE THREAD

**Issue by rphlmr** [rphlmr/supa-stripe-stack#14]

**Comment by AdityaSaroj** [comment]
Hey @rphlmr, did you get the time to address this? I tried to get the project running but I get another error after I fix one. It's a domino effect.

**Comment by rphlmr** [comment]
Hello,

I'll try to find some time this holidays.

I'm pretty sure Daniel is up to date on his stack https://github.com/dev-xo/stripe-stack

**Comment by rphlmr** [comment]
@AdityaSaroj It should be ok, let me know 😇

**Comment by AdityaSaroj** [comment]
Works perfectly. Thank you!
I did have to make a minor change in `package.json`
```
"seed": "tsx --require tsconfig-paths/register scripts/_seed.ts"
```
`ts-node` did not work for me for some reason.

**Comment by rphlmr** [comment]
> Works perfectly. Thank you!
> 
> I did have to make a minor change in `package.json`
> 
> ```
> 
> "seed": "tsx --require tsconfig-paths/register scripts/_seed.ts"
> 
> ```
> 
> `ts-node` did not work for me for some reason.

Thx. I will drop it for tsx.
