### ISSUE TITLE
Template's remix.init script failed

### ISSUE THREAD

**Issue by honzatmn** [rphlmr/supa-stripe-stack#17]
Hey @rphlmr , thanks for this starter!
I'm not sure what I'm doing wrong, but when I try to run `npx create-remix --template rphlmr/supa-stripe-stack`, I get an error:

```
▲  Oh no! Template's remix.init script failed
```

Thanks for any help!

**Comment by rphlmr** [comment]
Thanks for reporting!
Should be good now.
