### ISSUE TITLE
throw response.error vs return response.error

### ISSUE THREAD

**Issue by lhapaipai** [rphlmr/supa-stripe-stack#19]
Hello @rphlmr,
A big thank you for this super complete and very instructive example!!

I would like to have your opinion on the responses that you return from your `loader` and `action` functions
sometimes you use `throw` and other times `return` and I can't quite understand the logic.

from what i understand `return` would allow the `<NotifyError>` component to intervene. but in this case why not do it all the time? see also below, i have problems with this popup

```ts
// app/routes/api.subscribe.ts
export async function action({ request }: ActionFunctionArgs) {

  try {
    // ...

    if (subscription?.priceId === priceId) {
      throw new SupaStripeStackError({
        message: "You are already subscribed to this tier",
        metadata: { priceId },
        tag: "Subscribe API",
      });
    }

    return response.redirect(url, { authSession });
  } catch (cause) {
    return response.error(cause, { authSession });

    // equivalent
    return json(
      { error: { message, metadata, traceId } },
      // and authSession logic
    )
  }
}
```
```ts
// root.tsx
function NotifyError() {
  const [show, setShow] = useState(false);
  const fetchers = useFetchers();

  // f.data.error exists for a very, very short time but since `useFetchers()` (plurial version)
  // only returns actions that are not idle the error disappears immediately
  const error = fetchers.map((f) => (f.data as CatchResponse | null)?.error)[0];

  useEffect(() => {
    if (error) {
      setShow(true);
    } else {
      setShow(false);
    }
  }, [error]);

  return (
    <Transition show={show}>
      <p>An error occurred 😫</p>
      <p>{error?.message}</p>
      <div>
        <button onClick={() => setShow(false)}>x</button>
      </div>
    </Transition>
  );
}
```

if instead of `return response.error(cause, { authSession });` we had placed the code `throw response.error(cause, { authSession });` our router would have gone to the nearest ErrorBoundary (there is none in this example but we imagine that there would be one. also our `<NotifyError>` component does not intervene at all.

Do you have any clues to enlighten me?
A big thank you!!

**Comment by rphlmr** [comment]
Hi 👋
Sorry if it feels complicated sometimes 😬

I have a 'simple rule':
- Every loader that is not in a resource route throws an error, falling to the closest ErrorBoundary.
- Every loader that is in a resource route returns an error (they are like APIs).
- Every action returns an error

For the action, I return because I want to stay in the same context. I don't want my page to change.
For example, if my form submission returns an error, I want to display a toast and be able to retry, not replacing the view with something else (ErrorBoundary).

I find ErrorBoundary really cool when a route loader throws an error. Instead of dealing with nullable `loaderData`, you have your route (component) with the happy path and ErrorBoundary with the fail path.

**Comment by rphlmr** [comment]
If you want to dive into a deeper real-world example, you can check https://github.com/Shelf-nu/shelf.nu
It uses an evolution of my `response.xx` pattern.

A more detailed 'spec' of this pattern: https://github.com/rphlmr/remix-data-or-error-pattern/blob/main/app/routes/_index.tsx
(Note: Remix now has a `data` function, but it is not related to the one in these example projects.)

**Comment by lhapaipai** [comment]
good evening @rphlmr,
thanks for the clarification, I didn't understand the difference with resources and it seems completely understandable now.

Thanks also for sharing other resources. I didn't notice that you had made other repo on Remix, that will make for some reading..
good evening!!
